---
title: "GIS Portfolio"
output:
  html_document:
    toc: true  
    toc_float: true  
---
# __Rail trail__
## Metadata
- __Course name and code:__ Geo Tools
- __Application of the products:__
- __Potential users and their requirements:__ 
- __Motivation for choice of visualisation type:__ 
- __Dataset(s) used:__ 
- __Processing method(s):__ 
- __Tools used for implementation:__ 
- __Reflection on final result:__ 


# __Near-Real-Time temperature interpolation__

## Metadata
- __Course name and code:__ Advanced GIS for Earth and Environment
- __Application of the products:__
- __Potential users and their requirements:__ Anyone interested in current temperature at any country is a potential user. Such a user wants to quickly understand the temperature from the map.
- __Motivation for choice of visualisation type:__ Colours chosen are related to temperature (blue=cold, and red=warm)
- __Dataset(s) used:__ Open Weather near real time data
- __Processing method(s):__ Read temperature data from API, select data for chosen location, interpolate,.....
- __Tools used for implementation:__ R(owm,gstat,shiny), shinny app
- __Reflection on final result:__ The app is still very slow due to the large computation time of the interpolation, especially when kriging is selected. Nevertheless, it does its function: show temperature near real time (15-30 min difference with real time). The selection of method and country is user friendly, nevertheless, it could still be improved, as there is no action button, to click when user wants apply a change, and the countries are searched by code, it would be more user friendly for the user to be able to write the country name instead.

https://tubau001.shinyapps.io/real-time-temperature

# __Flooding Modelling__
## Metadata
- __Course name and code:__ Modelling and geo statistics
- __Application of the products:__
- __Potential users and their requirements:__ 
- __Motivation for choice of visualisation type:__ 
- __Dataset(s) used:__ 
- __Processing method(s):__ 
- __Tools used for implementation:__ 
- __Reflection on final result:__ 
